### PR TITLE
FIX: Fixes #124 Bad data-url encoding causes CMS page-search bug.

### LINKED ISSUE #124: CMS Page Filter is broken
If I install Fluent in SS 3.1.12, I can no longer filter on PageTypes or perform a standard "Content" text search from within the CMS' "Filter" located in the centre pane. Instead, a complete list of _all_ page objects is returned as if I had instructed the CMS to build me the standard SiteTree. It isn't even a search-result that I can "clear".

I can try and futz the URL to include/exclude the "l" parameter to no avail e.g. 

`/?locale=en_NZ&q[FilterClass]=CMSSiteTreeFilter_Search&q[ClassName]=MyPageType`

or 

`/?locale=en_NZ&l=en_NZ&q[FilterClass]=CMSSiteTreeFilter_Search&q[ClassName]=MyPageType`

Removing the module, and it works again. By "Remove" I mean delete the "fluent" directory.

### PR DESCRIPTION
**Pull request by phptek**

### CODE REVIEW

**Comment by tractorcow** [comment]
Ok, it looks like the actual bug is in `$.path.addSearchParams(url, param);` in https://github.com/silverstripe/silverstripe-framework/blob/3.2/admin/javascript/lib.js#L164

It doesn't seem to know how to add the `&l=en_US` to a querystring that contains escaped components. It ends up double-escaping each rather than simply appending the additional param.

I suggest to instead fix this in the fluent `urlForLocale` method to manually add the parameter, rather than using the lib.js version. It'd probably be as simple as checking if we should use `?` or `&` and then adding the param on the end of the url (but before the hash).

I am worried that, although the suggested fix does fix this issue, it feels like the problem is being fixed in the wrong place.

**Comment by phptek** [comment]
@tractorcow Fair enough :-) As it is though, I'm having to run a Gitlab fork with outstanding (incorrect) PRs merged there, because I don't have much more time to spend patching some of the issues I find (and I _know_ my client will find) perhaps to your honourable satisfaction :-)

The more important one I'm keen to see you respond to is #131.

Thanks man :-)

**Comment by tractorcow** [comment]
Fixed with https://github.com/tractorcow/silverstripe-fluent/commit/32778f8ea91e3332db17af7efaf07d28e31ddfb4

**Comment by tractorcow** [comment]
Well I've pushed up a fix to this issue, as well as merging #130.

I hope you can continue your work now. :D

**Pull request closed without merging**
