### PR TITLE
FIX: $manipulation updated for empty fields

### LINKED ISSUE #204: Unable to totally clear a translated field while Fluent is installed
No matter what I try, nor what Fluent commit I revert to, I cannot clear the value of a translated field via the CMS.

### Env

FlientLocale Cookie: en_NZ
SilverStripe 3.2.1
Fluent: 3.4.0 (Also tried master)
PHP 5.6 / Ubuntu 14.04
MySQL 5.5.49-0ubuntu0.14.04.1
Extensions applied:
  SiteTree:
    - FluentFilteredExtension
    - MyFluentExtension

1) Edit a translated field in the CMS for a page, Save & Publish = OK.

    mysql> SELECT ID,Fax,Fax_en_NZ FROM Page WHERE ID = 1208 UNION SELECT   ID,Fax,Fax_en_NZ FROM yPage_Live WHERE ID = 1208;

    +------+----------+-----------+
    | ID   | Fax      | Fax_en_NZ |
    +------+----------+-----------+
    | 1208 | 55512345 | 55512345  |
    +------+----------+-----------+

2) Edit a translated field again in the CMS for a page, down to a single character, Save & Publish = OK.

    mysql> SELECT ID,Fax,Fax_en_NZ FROM Page WHERE ID = 1208 UNION SELECT ID,Fax,Fax_en_NZ FROM Page_Live WHERE ID = 1208;

    +------+----------+-----------+
    | ID   | Fax      | Fax_en_NZ |
    +------+----------+-----------+
    | 1208 | 5        | 5         |
    | 1208 | 55512345 | 55512345  |
    +------+----------+-----------+

3) Edit a translated field again in the CMS for a page, but remove ALL characters (empty the field), Save & Publish = FAIL. 

The fields "Fax" and "Fax_en_NZ" on Page_Live both seem to retain the value of the most recent edit (From last entry in Page_versions AFAIKT) but draft table ("Page") shows correct NULL value for the "Fax" field. No matter how often this is repeated, the Page_Live field can never seem to be truncated via the CMS.

    mysql> SELECT ID,Fax,Fax_en_NZ FROM Page WHERE ID = 1208 UNION SELECT ID,Fax,Fax_en_NZ FROM Page_Live WHERE ID = 1208;

    +------+------+-----------+
    | ID   | Fax  | Fax_en_NZ |
    +------+------+-----------+
    | 1208 | NULL | 5         |
    | 1208 | 5    | 5         |
    +------+------+-----------+

### Scenarios

1. [FAIL] Remove / comment all project-specific fluent mods, YML config etc, keeping Fluent 3.4.0
2. [OK] Remove fluent itself
3. [FAIL] Put fluent back, upgrade to dev-master
4. [FAIL] Checkout suspect Fluent commit: 5856da69b14
5. [FAIL] Checkout suspect Fluent commit: e49dccb7066
6. [FAIL] Checkout suspect Fluent commit: 4a69d193df7
7. [OK] Remove fluent
8. [FAIL] Put Fluent back in again, sans custom config of any kind

### PR DESCRIPTION
**Pull request by mleutenegger**
Fixed an issue where deleting all text in a translated field and saving the object did not update the locale field in the DB. Fixes #204

### CODE REVIEW

**Comment by phptek** [comment]
I had to take a refresher on `array_key_exists` vs `isset`, sounds like this might actually be a fix.

**Comment by tractorcow** [comment]
I was actually going to look at nullable fields today :D

The other end of the fix will be making sure that empty fields stay empty in the frontend (on read).

**Comment by tractorcow** [comment]
> Looks good to me, but I'll leave merging to @tractorcow

Yeah, probably anything low-level ORM related might be best for me. :D

**Comment by mleutenegger** [comment]
Thanks!

**Comment by tractorcow** [comment]
See https://github.com/tractorcow/silverstripe-fluent/pull/225 for rest of the fix

**Comment by dhensby** [comment]
So it seems the key 'fields' isn't always set and so this fix has caused a regression #226

**Pull request merged**
