### PR TITLE
Fixed fluent dropdown presence on collapsed cms-menu

### PR DESCRIPTION
**Pull request by ARNHOE**
In 3.2 when cms-menu was collapsed, the fluent dropdown would drop all the menu items out of vision.

Before:

schermafbeelding 2015-07-26 om 14 39 20

After:

schermafbeelding 2015-07-26 om 14 34 56

### CODE REVIEW

**Comment by tractorcow** [comment]
Oh hi @ARNHOE :dancer: 
You mean, fluent even works on 3.2? =O

**Comment by tractorcow** [comment]
Postgres is broken at the moment; Ignoring this for the time being.

**Comment by ARNHOE** [comment]
Haiiii @tractorcow :p

So far everything is working, but if I come up some problems ill see if I can pr a fix.

**Comment by tractorcow** [comment]
Lots of things are fixed in fluent since I last spoke to you. ;)

I'll be trying to get a "reset translations" button working soon.

**Comment by ARNHOE** [comment]
I've been keeping track on pretty much every change just like before. Only from the background now I guess :p

Used it on multiple projects, hit me up on skype ;)

**Pull request merged**
