### PR TITLE
fix bad xml markup in GoogleSitemapController

### PR DESCRIPTION
**Pull request by Zazama**
fixing issue #455

### CODE REVIEW

**Comment by ScopeyNZ** [comment]
Thanks for the PR! Do you mind rebasing this patch against 4.1? It's a bugfix so we could release it in a minor version (eg 4.1.6) but we tag those from the 4.1 branch.

**Comment by Zazama** [comment]
Yeah I'd do that but I actually don't know how to with an already created pull request, do you mind helping me out?

**Comment by ScopeyNZ** [comment]
You can just rebase your branch with git (`git rebase HEAD~1 --onto 4.1`), do a force push (`git push -f`) to your fork then you just need to edit the PR and change the base branch (I can do that for you if you can't find the option).

**Comment by robbieaverill** [comment]
Please ensure you make the same PR to the google site maps module as well. This template is mostly copy pasted from that module with some fluent tweaks

**Comment by robbieaverill** [comment]
I've noticed that you've created this pull request from one of the "core branches" rather than a branch specifically intended for this pull request. This will cause problems for you to target this PR at a different branch.

You may need to close this pull request and create a new one against the correct branch - ensure you create a new branch for your pull request. See our [guide about contributing PRs](https://docs.silverstripe.org/en/4/contributing/code/#step-by-step-from-forking-to-sending-the-pull-request)

**Pull request closed without merging**
