### PR TITLE
API Enable the default locale to omit the prefix

### LINKED ISSUE #109: How to set empty aliase for default_locale ?
Hi 
my page has URL ru/about-us and en/about-us
I ned change it to /about-us and en/about-us (remove aliases from default locale)
I have next config
```
default_locale: ru_RU
  locales:
    - ru_RU
    - en_US
  aliases:
    ru_RU: 'ru'
    en_US: 'en'
```
if I change 
```
...
 aliases:
    ru_RU: ''
...
```
it not change URL to /about-us, it become ru-RU/about-us

### PR DESCRIPTION
**Pull request by tractorcow**
Fixes #109

@robbieaverill Do you want to test this feature out?

### CODE REVIEW

**Comment by tractorcow** [comment]
Oh nice, green tick :)

@prij can you help me to test this?

**Comment by prij** [comment]
@tractorcow yes I can do this next week

**Comment by robbieaverill** [comment]
@tractorcow I can apply it to my working SS set and monitor for any surprises. The unit test coverage looks like it should be OK though! *cough* PSR-2..

**Comment by tractorcow** [comment]
I'll do PSR-2 in another commit.

**Comment by tractorcow** [comment]
I think I'll just merge this and I'll stabilise later. :D

**Pull request merged**
